# Generated by Django 3.1.5 on 2024-05-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20240528_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='employer',
            name='bio',
            field=models.CharField(max_length=255),
        ),
    ]
