# Generated by Django 5.0.4 on 2024-06-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_auto_20240529_1823"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="required_applicants",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="application",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
